/*   Message file for the CODE library.
/*
msg err1
  lan english -def
    Memory, address space, or region "%p1s" was previously defined, on
    line %p2i of file "%p3s".
msg err2
  lan english -def
    Memory "%p1s" is not defined.
msg err3
  lan english -def
    "%p1s" is not a memory.
msg err4
  lan english -def
    Memory region "%p1s" is not defined.
msg err5
  lan english -def
    "%p1s" is not a memory region.
msg err6
  lan english -def
    Address space "%p1s" is not defined.
msg err7
  lan english -def
    "%p1s" is not a address space.
msg err8
  lan english -def
    Address region "%p1s" is not defined.
msg err9
  lan english -def
    "%p1s" is not a address region.
msg err10
  lan english -def
    Memory region "%p2s" was previously mapped to from address region "%p1s".
msg err11
  lan english -def
    Symbol "%p1s" already exists, defined on line %p2i of file "%p3s".
